title: "Harold B. Lee Library Collection Development"

base_url: "hbll-collection-development.github.io"

permalink: /:title

compress_html:
  clippings: all
  endings: all
  startings: [html, head, body]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "policy"
      permalink: /policies/:title/
      is_post: true
